### PR TITLE
Fix a lot of issues

### LINKED ISSUE #21: Creating layers with an empty name is possible
Since they don't have a name, they can't be selected, edited or deleted.

### PR DESCRIPTION
**Pull request by aleokdev**
Also fixes #21

### CODE REVIEW

**Comment by aleokdev** [comment]
Important TODO: Change version to 0.1.4

File: editor/src/map_manager.cpp [hunk 1]
```diff
@@ -233,9 +235,9 @@ static void show_map_layer_list() {
                         layer.visible = !layer.visible;
                     }
                     ImGui::SameLine();
-                    if (l == current_layer_selected ? ImGui::TextUnformatted(layer.name.c_str())
-                                                    : ImGui::TextDisabled("%s", layer.name.c_str()),
+                    if (ImGui::Selectable(layer.name.c_str(), l == current_layer_selected),
```
Comment (aleokdev) [inline editor/src/map_manager.cpp:238]: This fixes #21
